### ISSUE TITLE
Cmd showing this

### ISSUE THREAD

**Issue by Harsh-beep** [myogeshchavan97/spotify-music-search-app#3]
Failed to compile.

./src/components/Home.js
Attempted import error: 'Redirect' is not exported from 'react-router-dom'.

**Comment by myogeshchavan97** [comment]
@Harsh-beep you need to use react-router-dom version 5 which you can install using `yarn add react-router-dom@5.2.0 @5.2.0` or `npm install react-router-dom@5.2.0`.

Looks like you're using version 6 of react-router-dom.

For Version 6 of react-router-dom you need to use `Navigate` component instead of `Redirect`. This repository code is using version 5 of react-router-dom. So make sure to install that.
